# Default third-party paths (override with -DVAR=... on the cmake command line).
if(NOT DEFINED CMAKE_DIR)
    set(CMAKE_DIR "D:/win10/cmake-4.3.2-windows-x86_64/bin/cmake.exe" CACHE FILEPATH "CMake executable")
endif()
if(NOT DEFINED NINJA_EXE)
    set(NINJA_EXE "D:/win10/ninja.exe" CACHE FILEPATH "Ninja executable")
endif()
if(NOT DEFINED OPENCV_DIR)
    set(OPENCV_DIR "D:/win10/opencv500/build" CACHE PATH "OpenCV build directory (OpenCVConfig.cmake)")
endif()
if(NOT DEFINED EIGEN3_INCLUDE_DIR)
    set(EIGEN3_INCLUDE_DIR "D:/win10/deps_MD/eigen/eigen3.3.7_msvc2015_x64" CACHE PATH "Eigen3 include directory")
endif()
if(NOT DEFINED GFLAGS_ROOT)
    set(GFLAGS_ROOT "D:/win10/deps_MD/gflags-2.2.2msvcX64/gflags_2.2.2_MSVC_CXX_19.44.35211.0__x64_install" CACHE PATH "gflags install prefix")
endif()
if(NOT DEFINED GLOG_ROOT)
    set(GLOG_ROOT "D:/win10/deps_MD/glog-0.4.0_msvcx64NoGflags/glog_0.4.0_MSVC_C_19.44.35211.0_CXX_19.44.35211.0__x64_install" CACHE PATH "glog install prefix")
endif()
if(NOT DEFINED ZLIB_ROOT)
    set(ZLIB_ROOT "D:/win10/deps_MD/zlib__Vs2022_Ver_debug" CACHE PATH "zlib install prefix")
endif()
if(NOT DEFINED GTEST_ROOT)
    set(GTEST_ROOT "D:/win10/deps_MD/googletestV1.12.1Shared/googletest_MSVC_C_19.44.35211.0_CXX_19.44.35211.0x64" CACHE PATH "GoogleTest install prefix")
endif()

# Fallback when opencv500 is not present.
if(NOT EXISTS "${OPENCV_DIR}/OpenCVConfig.cmake")
    set(_opencv_fallback "D:/win10/opencv4130/build")
    if(EXISTS "${_opencv_fallback}/OpenCVConfig.cmake")
        message(STATUS "OPENCV_DIR not found, using fallback: ${_opencv_fallback}")
        set(OPENCV_DIR "${_opencv_fallback}" CACHE PATH "OpenCV build directory" FORCE)
    endif()
endif()

# Prefer vc16 import config when using prebuilt Windows pack.
if(EXISTS "${OPENCV_DIR}/x64/vc16/lib/OpenCVConfig.cmake")
    set(OpenCV_DIR "${OPENCV_DIR}/x64/vc16/lib" CACHE PATH "OpenCV package dir" FORCE)
endif()
