# Project version ¡ª shown in About dialog and Windows resource version block.
set(OBJECTRECOSTUDY_VERSION_MAJOR 1)
set(OBJECTRECOSTUDY_VERSION_MINOR 2)
set(OBJECTRECOSTUDY_VERSION_PATCH 0)
set(OBJECTRECOSTUDY_VERSION "${OBJECTRECOSTUDY_VERSION_MAJOR}.${OBJECTRECOSTUDY_VERSION_MINOR}.${OBJECTRECOSTUDY_VERSION_PATCH}")
